name: Build and Release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: |
          nix build
          cp -L result/vmlinuz vmlinuz
          cp -L result/initrd.img initrd.img
          cp -L result/seed.raw.zst seed.raw.zst

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            vmlinuz
            initrd.img
            seed.raw.zst
